# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Contract.ui'
#
# Created: Sat Nov 28 16:57:14 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui     

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1199, 744)
        self.gridLayoutWidget = QtGui.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 250, 801, 231))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.descriptionTextBrowser = QtGui.QTextBrowser(self.gridLayoutWidget)
        self.descriptionTextBrowser.setObjectName(_fromUtf8("descriptionTextBrowser"))
        self.gridLayout.addWidget(self.descriptionTextBrowser, 0, 0, 1, 1)
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 161, 181))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.verticalLayoutWidget_3 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(160, 0, 331, 181))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.itemName = QtGui.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.itemName.setFont(font)
        self.itemName.setText(_fromUtf8(""))
        self.itemName.setObjectName(_fromUtf8("itemName"))
        self.verticalLayout_3.addWidget(self.itemName)
        self.price = QtGui.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.price.setFont(font)
        self.price.setText(_fromUtf8(""))
        self.price.setObjectName(_fromUtf8("price"))
        self.verticalLayout_3.addWidget(self.price)
        self.dateUploaded = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.dateUploaded.setText(_fromUtf8(""))
        self.dateUploaded.setObjectName(_fromUtf8("dateUploaded"))
        self.verticalLayout_3.addWidget(self.dateUploaded)
        self.expires = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.expires.setText(_fromUtf8(""))
        self.expires.setObjectName(_fromUtf8("expires"))
        self.verticalLayout_3.addWidget(self.expires)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(0, 220, 91, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 500, 801, 151))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pictureOne = QtGui.QLabel(self.horizontalLayoutWidget)
        self.pictureOne.setText(_fromUtf8(""))
        self.pictureOne.setObjectName(_fromUtf8("pictureOne"))
        self.horizontalLayout.addWidget(self.pictureOne)
        self.pictureTwo = QtGui.QLabel(self.horizontalLayoutWidget)
        self.pictureTwo.setText(_fromUtf8(""))
        self.pictureTwo.setObjectName(_fromUtf8("pictureTwo"))
        self.horizontalLayout.addWidget(self.pictureTwo)
        self.pictureThree = QtGui.QLabel(self.horizontalLayoutWidget)
        self.pictureThree.setText(_fromUtf8(""))
        self.pictureThree.setObjectName(_fromUtf8("pictureThree"))
        self.horizontalLayout.addWidget(self.pictureThree)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(0, 480, 66, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(0, 670, 121, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.desiredQuantitySpinBox = QtGui.QSpinBox(Form)
        self.desiredQuantitySpinBox.setGeometry(QtCore.QRect(130, 660, 71, 31))
        self.desiredQuantitySpinBox.setObjectName(_fromUtf8("desiredQuantitySpinBox"))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(210, 710, 131, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.noteForMerchantLineEdit = QtGui.QLineEdit(Form)
        self.noteForMerchantLineEdit.setGeometry(QtCore.QRect(350, 710, 321, 27))
        self.noteForMerchantLineEdit.setObjectName(_fromUtf8("noteForMerchantLineEdit"))
        self.purchaseButton = QtGui.QPushButton(Form)
        self.purchaseButton.setGeometry(QtCore.QRect(690, 710, 98, 27))
        self.purchaseButton.setObjectName(_fromUtf8("purchaseButton"))
        self.sellerAvatar = QtGui.QLabel(Form)
        self.sellerAvatar.setGeometry(QtCore.QRect(990, 10, 201, 181))
        self.sellerAvatar.setText(_fromUtf8(""))
        self.sellerAvatar.setObjectName(_fromUtf8("sellerAvatar"))
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(210, 670, 81, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.keywords = QtGui.QLineEdit(Form)
        self.keywords.setGeometry(QtCore.QRect(350, 670, 321, 27))
        self.keywords.setObjectName(_fromUtf8("keywords"))
        self.gridLayoutWidget_2 = QtGui.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(490, 0, 471, 251))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.sellerName = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.sellerName.setFont(font)
        self.sellerName.setText(_fromUtf8(""))
        self.sellerName.setObjectName(_fromUtf8("sellerName"))
        self.gridLayout_2.addWidget(self.sellerName, 0, 1, 1, 1)
        self.bitcoinReceivingAddress = QtGui.QTextBrowser(self.gridLayoutWidget_2)
        self.bitcoinReceivingAddress.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.bitcoinReceivingAddress.setObjectName(_fromUtf8("bitcoinReceivingAddress"))
        self.gridLayout_2.addWidget(self.bitcoinReceivingAddress, 3, 1, 1, 1)
        self.guid = QtGui.QTextBrowser(self.gridLayoutWidget_2)
        self.guid.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.guid.setObjectName(_fromUtf8("guid"))
        self.gridLayout_2.addWidget(self.guid, 2, 1, 1, 1)
        self.sellerEmail = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sellerEmail.setFont(font)
        self.sellerEmail.setText(_fromUtf8(""))
        self.sellerEmail.setObjectName(_fromUtf8("sellerEmail"))
        self.gridLayout_2.addWidget(self.sellerEmail, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.publicKey = QtGui.QTextBrowser(self.gridLayoutWidget_2)
        self.publicKey.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.publicKey.setObjectName(_fromUtf8("publicKey"))
        self.gridLayout_2.addWidget(self.publicKey, 4, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 4, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "Item Name:", None))
        self.label_2.setText(_translate("Form", "Price:", None))
        self.label_3.setText(_translate("Form", "Date Uploaded:", None))
        self.label_4.setText(_translate("Form", "Expires:", None))
        self.label_6.setText(_translate("Form", "Description: ", None))
        self.label_7.setText(_translate("Form", "Pictures:", None))
        self.label_8.setText(_translate("Form", "Desired Quantity:", None))
        self.label_9.setText(_translate("Form", "Note for Merchant:", None))
        self.purchaseButton.setText(_translate("Form", "Purchase", None))
        self.label_15.setText(_translate("Form", "Keywords:", None))
        self.bitcoinReceivingAddress.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">asdfsdddddddddddddddddddddddddddddddddddddddddddddddddasdfasdfasdfasdfasdfasdfasdffdasdf</p></body></html>", None))
        self.guid.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">asdfsddddddddddddddddddddddddddddddddddddddddddddddddd</p></body></html>", None))
        self.label_13.setText(_translate("Form", "GUID:", None))
        self.publicKey.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">asdfsddddddddddddddddddddddddddddddddddddddddddddddddd</p></body></html>", None))
        self.label_11.setText(_translate("Form", "Seller Email:", None))
        self.label_10.setText(_translate("Form", "Seller Name:", None))
        self.label_12.setText(_translate("Form", "Bitcoin Receiving Address:", None))
        self.label_14.setText(_translate("Form", "Public Key:", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

